"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from coval_sdk.models.coval_reports_api_create_report_request import CovalReportsAPICreateReportRequest
from coval_sdk.models.coval_reports_api_create_report_response import CovalReportsAPICreateReportResponse
from coval_sdk.models.coval_reports_api_delete_report_response import CovalReportsAPIDeleteReportResponse
from coval_sdk.models.coval_reports_api_get_report_response import CovalReportsAPIGetReportResponse
from coval_sdk.models.coval_reports_api_list_report_rows_response import CovalReportsAPIListReportRowsResponse
from coval_sdk.models.coval_reports_api_list_reports_response import CovalReportsAPIListReportsResponse
from coval_sdk.models.coval_reports_api_update_report_request import CovalReportsAPIUpdateReportRequest
from coval_sdk.models.coval_reports_api_update_report_response import CovalReportsAPIUpdateReportResponse

from coval_sdk.api_client import ApiClient, RequestSerialized
from coval_sdk.api_response import ApiResponse
from coval_sdk.rest import RESTResponseType


class ReportsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def create_report(
        self,
        coval_reports_api_create_report_request: CovalReportsAPICreateReportRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CovalReportsAPICreateReportResponse:
        """Create report

        Create a saved report from existing run IDs. All runs must belong to the authenticated organization. Public reports are shareable without login and mark their included runs public. 

        :param coval_reports_api_create_report_request: (required)
        :type coval_reports_api_create_report_request: CovalReportsAPICreateReportRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_report_serialize(
            coval_reports_api_create_report_request=coval_reports_api_create_report_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CovalReportsAPICreateReportResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def create_report_with_http_info(
        self,
        coval_reports_api_create_report_request: CovalReportsAPICreateReportRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CovalReportsAPICreateReportResponse]:
        """Create report

        Create a saved report from existing run IDs. All runs must belong to the authenticated organization. Public reports are shareable without login and mark their included runs public. 

        :param coval_reports_api_create_report_request: (required)
        :type coval_reports_api_create_report_request: CovalReportsAPICreateReportRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_report_serialize(
            coval_reports_api_create_report_request=coval_reports_api_create_report_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CovalReportsAPICreateReportResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def create_report_without_preload_content(
        self,
        coval_reports_api_create_report_request: CovalReportsAPICreateReportRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create report

        Create a saved report from existing run IDs. All runs must belong to the authenticated organization. Public reports are shareable without login and mark their included runs public. 

        :param coval_reports_api_create_report_request: (required)
        :type coval_reports_api_create_report_request: CovalReportsAPICreateReportRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_report_serialize(
            coval_reports_api_create_report_request=coval_reports_api_create_report_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CovalReportsAPICreateReportResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _create_report_serialize(
        self,
        coval_reports_api_create_report_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if coval_reports_api_create_report_request is not None:
            _body_params = coval_reports_api_create_report_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'Coval_Reports_API_ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/reports',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def delete_report(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CovalReportsAPIDeleteReportResponse:
        """Delete report

        Soft-delete a saved report. If the report is public, its run visibility is revoked unless another public report still references the same runs. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_report_serialize(
            report_id=report_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIDeleteReportResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def delete_report_with_http_info(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CovalReportsAPIDeleteReportResponse]:
        """Delete report

        Soft-delete a saved report. If the report is public, its run visibility is revoked unless another public report still references the same runs. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_report_serialize(
            report_id=report_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIDeleteReportResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def delete_report_without_preload_content(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Delete report

        Soft-delete a saved report. If the report is public, its run visibility is revoked unless another public report still references the same runs. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_report_serialize(
            report_id=report_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIDeleteReportResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _delete_report_serialize(
        self,
        report_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if report_id is not None:
            _path_params['report_id'] = report_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Coval_Reports_API_ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='DELETE',
            resource_path='/reports/{report_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_report(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CovalReportsAPIGetReportResponse:
        """Get report

        Retrieve a saved report by ID, including its complete supported view and metric configuration. The response includes a strong `ETag`; send that value in `If-Match` when patching `view_config`. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_report_serialize(
            report_id=report_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIGetReportResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_report_with_http_info(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CovalReportsAPIGetReportResponse]:
        """Get report

        Retrieve a saved report by ID, including its complete supported view and metric configuration. The response includes a strong `ETag`; send that value in `If-Match` when patching `view_config`. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_report_serialize(
            report_id=report_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIGetReportResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_report_without_preload_content(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get report

        Retrieve a saved report by ID, including its complete supported view and metric configuration. The response includes a strong `ETag`; send that value in `If-Match` when patching `view_config`. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_report_serialize(
            report_id=report_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIGetReportResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_report_serialize(
        self,
        report_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if report_id is not None:
            _path_params['report_id'] = report_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Coval_Reports_API_ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/reports/{report_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_report_rows(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        cursor: Annotated[Optional[StrictStr], Field(description="Opaque value from a prior response's `next_page_token`. It is numeric for run-backed reports and a simulation-ID keyset cursor for dynamic monitoring reports. ")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=2000, strict=True, ge=1)]], Field(description="Max rows per page (1-2000).")] = None,
        metric_ids: Annotated[Optional[StrictStr], Field(description="Comma-separated metric ids to include.")] = None,
        simulation_output_ids: Annotated[Optional[StrictStr], Field(description="Comma-separated simulation output ids to restrict to.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CovalReportsAPIListReportRowsResponse:
        """List report rows

        List a report's per-simulation rows, each with metric outputs inline. Run-backed reports retain offset-cursor behavior. Dynamic monitoring reports resolve their cohort from the report's saved monitoring filters, including saved date bounds, and use an opaque simulation-ID keyset cursor.  For metadata-grouped reports, read the grouping key from `report.view_config.metadata_key`; each row exposes the corresponding value in `metadata`. Optionally narrow returned metrics or simulations with the comma-separated query parameters. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param cursor: Opaque value from a prior response's `next_page_token`. It is numeric for run-backed reports and a simulation-ID keyset cursor for dynamic monitoring reports. 
        :type cursor: str
        :param limit: Max rows per page (1-2000).
        :type limit: int
        :param metric_ids: Comma-separated metric ids to include.
        :type metric_ids: str
        :param simulation_output_ids: Comma-separated simulation output ids to restrict to.
        :type simulation_output_ids: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_report_rows_serialize(
            report_id=report_id,
            cursor=cursor,
            limit=limit,
            metric_ids=metric_ids,
            simulation_output_ids=simulation_output_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIListReportRowsResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_report_rows_with_http_info(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        cursor: Annotated[Optional[StrictStr], Field(description="Opaque value from a prior response's `next_page_token`. It is numeric for run-backed reports and a simulation-ID keyset cursor for dynamic monitoring reports. ")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=2000, strict=True, ge=1)]], Field(description="Max rows per page (1-2000).")] = None,
        metric_ids: Annotated[Optional[StrictStr], Field(description="Comma-separated metric ids to include.")] = None,
        simulation_output_ids: Annotated[Optional[StrictStr], Field(description="Comma-separated simulation output ids to restrict to.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CovalReportsAPIListReportRowsResponse]:
        """List report rows

        List a report's per-simulation rows, each with metric outputs inline. Run-backed reports retain offset-cursor behavior. Dynamic monitoring reports resolve their cohort from the report's saved monitoring filters, including saved date bounds, and use an opaque simulation-ID keyset cursor.  For metadata-grouped reports, read the grouping key from `report.view_config.metadata_key`; each row exposes the corresponding value in `metadata`. Optionally narrow returned metrics or simulations with the comma-separated query parameters. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param cursor: Opaque value from a prior response's `next_page_token`. It is numeric for run-backed reports and a simulation-ID keyset cursor for dynamic monitoring reports. 
        :type cursor: str
        :param limit: Max rows per page (1-2000).
        :type limit: int
        :param metric_ids: Comma-separated metric ids to include.
        :type metric_ids: str
        :param simulation_output_ids: Comma-separated simulation output ids to restrict to.
        :type simulation_output_ids: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_report_rows_serialize(
            report_id=report_id,
            cursor=cursor,
            limit=limit,
            metric_ids=metric_ids,
            simulation_output_ids=simulation_output_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIListReportRowsResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_report_rows_without_preload_content(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        cursor: Annotated[Optional[StrictStr], Field(description="Opaque value from a prior response's `next_page_token`. It is numeric for run-backed reports and a simulation-ID keyset cursor for dynamic monitoring reports. ")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=2000, strict=True, ge=1)]], Field(description="Max rows per page (1-2000).")] = None,
        metric_ids: Annotated[Optional[StrictStr], Field(description="Comma-separated metric ids to include.")] = None,
        simulation_output_ids: Annotated[Optional[StrictStr], Field(description="Comma-separated simulation output ids to restrict to.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List report rows

        List a report's per-simulation rows, each with metric outputs inline. Run-backed reports retain offset-cursor behavior. Dynamic monitoring reports resolve their cohort from the report's saved monitoring filters, including saved date bounds, and use an opaque simulation-ID keyset cursor.  For metadata-grouped reports, read the grouping key from `report.view_config.metadata_key`; each row exposes the corresponding value in `metadata`. Optionally narrow returned metrics or simulations with the comma-separated query parameters. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param cursor: Opaque value from a prior response's `next_page_token`. It is numeric for run-backed reports and a simulation-ID keyset cursor for dynamic monitoring reports. 
        :type cursor: str
        :param limit: Max rows per page (1-2000).
        :type limit: int
        :param metric_ids: Comma-separated metric ids to include.
        :type metric_ids: str
        :param simulation_output_ids: Comma-separated simulation output ids to restrict to.
        :type simulation_output_ids: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_report_rows_serialize(
            report_id=report_id,
            cursor=cursor,
            limit=limit,
            metric_ids=metric_ids,
            simulation_output_ids=simulation_output_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIListReportRowsResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_report_rows_serialize(
        self,
        report_id,
        cursor,
        limit,
        metric_ids,
        simulation_output_ids,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if report_id is not None:
            _path_params['report_id'] = report_id
        # process the query parameters
        if cursor is not None:
            
            _query_params.append(('cursor', cursor))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if metric_ids is not None:
            
            _query_params.append(('metric_ids', metric_ids))
            
        if simulation_output_ids is not None:
            
            _query_params.append(('simulation_output_ids', simulation_output_ids))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Coval_Reports_API_ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/reports/{report_id}/rows',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_reports(
        self,
        cursor: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Cursor from the previous page.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum number of reports to return.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CovalReportsAPIListReportsResponse:
        """List reports

        Retrieve a paginated list of saved reports for the authenticated organization.

        :param cursor: Cursor from the previous page.
        :type cursor: str
        :param limit: Maximum number of reports to return.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_reports_serialize(
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIListReportsResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_reports_with_http_info(
        self,
        cursor: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Cursor from the previous page.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum number of reports to return.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CovalReportsAPIListReportsResponse]:
        """List reports

        Retrieve a paginated list of saved reports for the authenticated organization.

        :param cursor: Cursor from the previous page.
        :type cursor: str
        :param limit: Maximum number of reports to return.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_reports_serialize(
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIListReportsResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_reports_without_preload_content(
        self,
        cursor: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Cursor from the previous page.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum number of reports to return.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List reports

        Retrieve a paginated list of saved reports for the authenticated organization.

        :param cursor: Cursor from the previous page.
        :type cursor: str
        :param limit: Maximum number of reports to return.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_reports_serialize(
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIListReportsResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_reports_serialize(
        self,
        cursor,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if cursor is not None:
            
            _query_params.append(('cursor', cursor))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Coval_Reports_API_ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/reports',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def update_report(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        coval_reports_api_update_report_request: CovalReportsAPIUpdateReportRequest,
        if_match: Annotated[Optional[StrictStr], Field(description="Strong `ETag` from `GET /reports/{report_id}`. Required when the PATCH body contains `view_config`; omit for legacy non-configuration updates. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CovalReportsAPIUpdateReportResponse:
        """Update report

        Partially update a saved report. `view_config` is a typed, merge-only patch: omitted supported fields, unknown compatible stored view fields, `metric_config`, ownership, IDs, and permissions remain unchanged.  Send the `ETag` returned by `GET /reports/{report_id}` in `If-Match` whenever `view_config` is present. A stale value is rejected with 412. The legacy top-level `compare_by` and `metadata_key` fields remain available for backward compatibility. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param coval_reports_api_update_report_request: (required)
        :type coval_reports_api_update_report_request: CovalReportsAPIUpdateReportRequest
        :param if_match: Strong `ETag` from `GET /reports/{report_id}`. Required when the PATCH body contains `view_config`; omit for legacy non-configuration updates. 
        :type if_match: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_report_serialize(
            report_id=report_id,
            coval_reports_api_update_report_request=coval_reports_api_update_report_request,
            if_match=if_match,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIUpdateReportResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '412': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def update_report_with_http_info(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        coval_reports_api_update_report_request: CovalReportsAPIUpdateReportRequest,
        if_match: Annotated[Optional[StrictStr], Field(description="Strong `ETag` from `GET /reports/{report_id}`. Required when the PATCH body contains `view_config`; omit for legacy non-configuration updates. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CovalReportsAPIUpdateReportResponse]:
        """Update report

        Partially update a saved report. `view_config` is a typed, merge-only patch: omitted supported fields, unknown compatible stored view fields, `metric_config`, ownership, IDs, and permissions remain unchanged.  Send the `ETag` returned by `GET /reports/{report_id}` in `If-Match` whenever `view_config` is present. A stale value is rejected with 412. The legacy top-level `compare_by` and `metadata_key` fields remain available for backward compatibility. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param coval_reports_api_update_report_request: (required)
        :type coval_reports_api_update_report_request: CovalReportsAPIUpdateReportRequest
        :param if_match: Strong `ETag` from `GET /reports/{report_id}`. Required when the PATCH body contains `view_config`; omit for legacy non-configuration updates. 
        :type if_match: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_report_serialize(
            report_id=report_id,
            coval_reports_api_update_report_request=coval_reports_api_update_report_request,
            if_match=if_match,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIUpdateReportResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '412': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def update_report_without_preload_content(
        self,
        report_id: Annotated[str, Field(min_length=26, strict=True, max_length=26, description="Saved report ULID.")],
        coval_reports_api_update_report_request: CovalReportsAPIUpdateReportRequest,
        if_match: Annotated[Optional[StrictStr], Field(description="Strong `ETag` from `GET /reports/{report_id}`. Required when the PATCH body contains `view_config`; omit for legacy non-configuration updates. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Update report

        Partially update a saved report. `view_config` is a typed, merge-only patch: omitted supported fields, unknown compatible stored view fields, `metric_config`, ownership, IDs, and permissions remain unchanged.  Send the `ETag` returned by `GET /reports/{report_id}` in `If-Match` whenever `view_config` is present. A stale value is rejected with 412. The legacy top-level `compare_by` and `metadata_key` fields remain available for backward compatibility. 

        :param report_id: Saved report ULID. (required)
        :type report_id: str
        :param coval_reports_api_update_report_request: (required)
        :type coval_reports_api_update_report_request: CovalReportsAPIUpdateReportRequest
        :param if_match: Strong `ETag` from `GET /reports/{report_id}`. Required when the PATCH body contains `view_config`; omit for legacy non-configuration updates. 
        :type if_match: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_report_serialize(
            report_id=report_id,
            coval_reports_api_update_report_request=coval_reports_api_update_report_request,
            if_match=if_match,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalReportsAPIUpdateReportResponse",
            '400': "CovalReportsAPIErrorResponse",
            '401': "CovalReportsAPIErrorResponse",
            '403': "CovalReportsAPIErrorResponse",
            '404': "CovalReportsAPIErrorResponse",
            '412': "CovalReportsAPIErrorResponse",
            '500': "CovalReportsAPIErrorResponse",
            '503': "CovalReportsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _update_report_serialize(
        self,
        report_id,
        coval_reports_api_update_report_request,
        if_match,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if report_id is not None:
            _path_params['report_id'] = report_id
        # process the query parameters
        # process the header parameters
        if if_match is not None:
            _header_params['If-Match'] = if_match
        # process the form parameters
        # process the body parameter
        if coval_reports_api_update_report_request is not None:
            _body_params = coval_reports_api_update_report_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'Coval_Reports_API_ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='PATCH',
            resource_path='/reports/{report_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


