"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from coval_sdk.models.coval_scheduled_runs_api_create_scheduled_run_request import CovalScheduledRunsAPICreateScheduledRunRequest
from coval_sdk.models.coval_scheduled_runs_api_create_scheduled_run_response import CovalScheduledRunsAPICreateScheduledRunResponse
from coval_sdk.models.coval_scheduled_runs_api_get_scheduled_run_response import CovalScheduledRunsAPIGetScheduledRunResponse
from coval_sdk.models.coval_scheduled_runs_api_list_scheduled_runs_response import CovalScheduledRunsAPIListScheduledRunsResponse
from coval_sdk.models.coval_scheduled_runs_api_update_scheduled_run_request import CovalScheduledRunsAPIUpdateScheduledRunRequest
from coval_sdk.models.coval_scheduled_runs_api_update_scheduled_run_response import CovalScheduledRunsAPIUpdateScheduledRunResponse

from coval_sdk.api_client import ApiClient, RequestSerialized
from coval_sdk.api_response import ApiResponse
from coval_sdk.rest import RESTResponseType


class ScheduledRunsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def create_scheduled_run(
        self,
        coval_scheduled_runs_api_create_scheduled_run_request: CovalScheduledRunsAPICreateScheduledRunRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CovalScheduledRunsAPICreateScheduledRunResponse:
        """Create scheduled run

        Create a new scheduled run that will trigger evaluations on a recurring schedule.  The schedule is defined using either: - **Rate expressions**: `rate(15 minutes)`, `rate(1 hour)`, `rate(1 day)` - **Cron expressions**: `cron(0 9 ? * MON-FRI *)` (9am weekdays)  Schedules are created in an enabled state by default and will begin triggering at the next scheduled time. 

        :param coval_scheduled_runs_api_create_scheduled_run_request: (required)
        :type coval_scheduled_runs_api_create_scheduled_run_request: CovalScheduledRunsAPICreateScheduledRunRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_scheduled_run_serialize(
            coval_scheduled_runs_api_create_scheduled_run_request=coval_scheduled_runs_api_create_scheduled_run_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CovalScheduledRunsAPICreateScheduledRunResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def create_scheduled_run_with_http_info(
        self,
        coval_scheduled_runs_api_create_scheduled_run_request: CovalScheduledRunsAPICreateScheduledRunRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CovalScheduledRunsAPICreateScheduledRunResponse]:
        """Create scheduled run

        Create a new scheduled run that will trigger evaluations on a recurring schedule.  The schedule is defined using either: - **Rate expressions**: `rate(15 minutes)`, `rate(1 hour)`, `rate(1 day)` - **Cron expressions**: `cron(0 9 ? * MON-FRI *)` (9am weekdays)  Schedules are created in an enabled state by default and will begin triggering at the next scheduled time. 

        :param coval_scheduled_runs_api_create_scheduled_run_request: (required)
        :type coval_scheduled_runs_api_create_scheduled_run_request: CovalScheduledRunsAPICreateScheduledRunRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_scheduled_run_serialize(
            coval_scheduled_runs_api_create_scheduled_run_request=coval_scheduled_runs_api_create_scheduled_run_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CovalScheduledRunsAPICreateScheduledRunResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def create_scheduled_run_without_preload_content(
        self,
        coval_scheduled_runs_api_create_scheduled_run_request: CovalScheduledRunsAPICreateScheduledRunRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create scheduled run

        Create a new scheduled run that will trigger evaluations on a recurring schedule.  The schedule is defined using either: - **Rate expressions**: `rate(15 minutes)`, `rate(1 hour)`, `rate(1 day)` - **Cron expressions**: `cron(0 9 ? * MON-FRI *)` (9am weekdays)  Schedules are created in an enabled state by default and will begin triggering at the next scheduled time. 

        :param coval_scheduled_runs_api_create_scheduled_run_request: (required)
        :type coval_scheduled_runs_api_create_scheduled_run_request: CovalScheduledRunsAPICreateScheduledRunRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_scheduled_run_serialize(
            coval_scheduled_runs_api_create_scheduled_run_request=coval_scheduled_runs_api_create_scheduled_run_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CovalScheduledRunsAPICreateScheduledRunResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _create_scheduled_run_serialize(
        self,
        coval_scheduled_runs_api_create_scheduled_run_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if coval_scheduled_runs_api_create_scheduled_run_request is not None:
            _body_params = coval_scheduled_runs_api_create_scheduled_run_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'Coval_Scheduled_Runs_API_ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/scheduled-runs',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def delete_scheduled_run(
        self,
        scheduled_run_id: Annotated[str, Field(strict=True, description="Scheduled run resource ID")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Delete scheduled run

        Delete a scheduled run and remove its associated schedule.

        :param scheduled_run_id: Scheduled run resource ID (required)
        :type scheduled_run_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_scheduled_run_serialize(
            scheduled_run_id=scheduled_run_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def delete_scheduled_run_with_http_info(
        self,
        scheduled_run_id: Annotated[str, Field(strict=True, description="Scheduled run resource ID")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Delete scheduled run

        Delete a scheduled run and remove its associated schedule.

        :param scheduled_run_id: Scheduled run resource ID (required)
        :type scheduled_run_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_scheduled_run_serialize(
            scheduled_run_id=scheduled_run_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def delete_scheduled_run_without_preload_content(
        self,
        scheduled_run_id: Annotated[str, Field(strict=True, description="Scheduled run resource ID")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Delete scheduled run

        Delete a scheduled run and remove its associated schedule.

        :param scheduled_run_id: Scheduled run resource ID (required)
        :type scheduled_run_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_scheduled_run_serialize(
            scheduled_run_id=scheduled_run_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _delete_scheduled_run_serialize(
        self,
        scheduled_run_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if scheduled_run_id is not None:
            _path_params['scheduled_run_id'] = scheduled_run_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Coval_Scheduled_Runs_API_ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='DELETE',
            resource_path='/v1/scheduled-runs/{scheduled_run_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_scheduled_run(
        self,
        scheduled_run_id: Annotated[str, Field(strict=True, description="Scheduled run resource ID")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CovalScheduledRunsAPIGetScheduledRunResponse:
        """Get scheduled run

        Retrieve a specific scheduled run by ID.

        :param scheduled_run_id: Scheduled run resource ID (required)
        :type scheduled_run_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_scheduled_run_serialize(
            scheduled_run_id=scheduled_run_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalScheduledRunsAPIGetScheduledRunResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_scheduled_run_with_http_info(
        self,
        scheduled_run_id: Annotated[str, Field(strict=True, description="Scheduled run resource ID")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CovalScheduledRunsAPIGetScheduledRunResponse]:
        """Get scheduled run

        Retrieve a specific scheduled run by ID.

        :param scheduled_run_id: Scheduled run resource ID (required)
        :type scheduled_run_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_scheduled_run_serialize(
            scheduled_run_id=scheduled_run_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalScheduledRunsAPIGetScheduledRunResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_scheduled_run_without_preload_content(
        self,
        scheduled_run_id: Annotated[str, Field(strict=True, description="Scheduled run resource ID")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get scheduled run

        Retrieve a specific scheduled run by ID.

        :param scheduled_run_id: Scheduled run resource ID (required)
        :type scheduled_run_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_scheduled_run_serialize(
            scheduled_run_id=scheduled_run_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalScheduledRunsAPIGetScheduledRunResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_scheduled_run_serialize(
        self,
        scheduled_run_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if scheduled_run_id is not None:
            _path_params['scheduled_run_id'] = scheduled_run_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Coval_Scheduled_Runs_API_ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/scheduled-runs/{scheduled_run_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_scheduled_runs(
        self,
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum number of results per page")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Opaque pagination token from previous response")] = None,
        enabled: Annotated[Optional[StrictBool], Field(description="Filter by enabled state (true = active schedules, false = paused)")] = None,
        template_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by run template ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CovalScheduledRunsAPIListScheduledRunsResponse:
        """List scheduled runs

        Retrieve a paginated list of scheduled runs with optional filtering.

        :param page_size: Maximum number of results per page
        :type page_size: int
        :param page_token: Opaque pagination token from previous response
        :type page_token: str
        :param enabled: Filter by enabled state (true = active schedules, false = paused)
        :type enabled: bool
        :param template_id: Filter by run template ID
        :type template_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_scheduled_runs_serialize(
            page_size=page_size,
            page_token=page_token,
            enabled=enabled,
            template_id=template_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalScheduledRunsAPIListScheduledRunsResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_scheduled_runs_with_http_info(
        self,
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum number of results per page")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Opaque pagination token from previous response")] = None,
        enabled: Annotated[Optional[StrictBool], Field(description="Filter by enabled state (true = active schedules, false = paused)")] = None,
        template_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by run template ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CovalScheduledRunsAPIListScheduledRunsResponse]:
        """List scheduled runs

        Retrieve a paginated list of scheduled runs with optional filtering.

        :param page_size: Maximum number of results per page
        :type page_size: int
        :param page_token: Opaque pagination token from previous response
        :type page_token: str
        :param enabled: Filter by enabled state (true = active schedules, false = paused)
        :type enabled: bool
        :param template_id: Filter by run template ID
        :type template_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_scheduled_runs_serialize(
            page_size=page_size,
            page_token=page_token,
            enabled=enabled,
            template_id=template_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalScheduledRunsAPIListScheduledRunsResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_scheduled_runs_without_preload_content(
        self,
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum number of results per page")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Opaque pagination token from previous response")] = None,
        enabled: Annotated[Optional[StrictBool], Field(description="Filter by enabled state (true = active schedules, false = paused)")] = None,
        template_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by run template ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List scheduled runs

        Retrieve a paginated list of scheduled runs with optional filtering.

        :param page_size: Maximum number of results per page
        :type page_size: int
        :param page_token: Opaque pagination token from previous response
        :type page_token: str
        :param enabled: Filter by enabled state (true = active schedules, false = paused)
        :type enabled: bool
        :param template_id: Filter by run template ID
        :type template_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_scheduled_runs_serialize(
            page_size=page_size,
            page_token=page_token,
            enabled=enabled,
            template_id=template_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalScheduledRunsAPIListScheduledRunsResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_scheduled_runs_serialize(
        self,
        page_size,
        page_token,
        enabled,
        template_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if page_size is not None:
            
            _query_params.append(('page_size', page_size))
            
        if page_token is not None:
            
            _query_params.append(('page_token', page_token))
            
        if enabled is not None:
            
            _query_params.append(('enabled', enabled))
            
        if template_id is not None:
            
            _query_params.append(('template_id', template_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Coval_Scheduled_Runs_API_ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/scheduled-runs',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def update_scheduled_run(
        self,
        scheduled_run_id: Annotated[str, Field(strict=True, description="Scheduled run resource ID")],
        coval_scheduled_runs_api_update_scheduled_run_request: CovalScheduledRunsAPIUpdateScheduledRunRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CovalScheduledRunsAPIUpdateScheduledRunResponse:
        """Update scheduled run

        Update specific fields of an existing scheduled run.  Common use cases: - Enable/disable a schedule: `{\"enabled\": false}` - Change the schedule frequency: `{\"schedule_expression\": \"rate(1 hour)\"}` - Update the run template: `{\"run_template_id\": \"new_template_id\"}` 

        :param scheduled_run_id: Scheduled run resource ID (required)
        :type scheduled_run_id: str
        :param coval_scheduled_runs_api_update_scheduled_run_request: (required)
        :type coval_scheduled_runs_api_update_scheduled_run_request: CovalScheduledRunsAPIUpdateScheduledRunRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_scheduled_run_serialize(
            scheduled_run_id=scheduled_run_id,
            coval_scheduled_runs_api_update_scheduled_run_request=coval_scheduled_runs_api_update_scheduled_run_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalScheduledRunsAPIUpdateScheduledRunResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def update_scheduled_run_with_http_info(
        self,
        scheduled_run_id: Annotated[str, Field(strict=True, description="Scheduled run resource ID")],
        coval_scheduled_runs_api_update_scheduled_run_request: CovalScheduledRunsAPIUpdateScheduledRunRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CovalScheduledRunsAPIUpdateScheduledRunResponse]:
        """Update scheduled run

        Update specific fields of an existing scheduled run.  Common use cases: - Enable/disable a schedule: `{\"enabled\": false}` - Change the schedule frequency: `{\"schedule_expression\": \"rate(1 hour)\"}` - Update the run template: `{\"run_template_id\": \"new_template_id\"}` 

        :param scheduled_run_id: Scheduled run resource ID (required)
        :type scheduled_run_id: str
        :param coval_scheduled_runs_api_update_scheduled_run_request: (required)
        :type coval_scheduled_runs_api_update_scheduled_run_request: CovalScheduledRunsAPIUpdateScheduledRunRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_scheduled_run_serialize(
            scheduled_run_id=scheduled_run_id,
            coval_scheduled_runs_api_update_scheduled_run_request=coval_scheduled_runs_api_update_scheduled_run_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalScheduledRunsAPIUpdateScheduledRunResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def update_scheduled_run_without_preload_content(
        self,
        scheduled_run_id: Annotated[str, Field(strict=True, description="Scheduled run resource ID")],
        coval_scheduled_runs_api_update_scheduled_run_request: CovalScheduledRunsAPIUpdateScheduledRunRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Update scheduled run

        Update specific fields of an existing scheduled run.  Common use cases: - Enable/disable a schedule: `{\"enabled\": false}` - Change the schedule frequency: `{\"schedule_expression\": \"rate(1 hour)\"}` - Update the run template: `{\"run_template_id\": \"new_template_id\"}` 

        :param scheduled_run_id: Scheduled run resource ID (required)
        :type scheduled_run_id: str
        :param coval_scheduled_runs_api_update_scheduled_run_request: (required)
        :type coval_scheduled_runs_api_update_scheduled_run_request: CovalScheduledRunsAPIUpdateScheduledRunRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_scheduled_run_serialize(
            scheduled_run_id=scheduled_run_id,
            coval_scheduled_runs_api_update_scheduled_run_request=coval_scheduled_runs_api_update_scheduled_run_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CovalScheduledRunsAPIUpdateScheduledRunResponse",
            '400': "CovalScheduledRunsAPIErrorResponse",
            '401': "CovalScheduledRunsAPIErrorResponse",
            '404': "CovalScheduledRunsAPIErrorResponse",
            '500': "CovalScheduledRunsAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _update_scheduled_run_serialize(
        self,
        scheduled_run_id,
        coval_scheduled_runs_api_update_scheduled_run_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if scheduled_run_id is not None:
            _path_params['scheduled_run_id'] = scheduled_run_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if coval_scheduled_runs_api_update_scheduled_run_request is not None:
            _body_params = coval_scheduled_runs_api_update_scheduled_run_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'Coval_Scheduled_Runs_API_ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='PATCH',
            resource_path='/v1/scheduled-runs/{scheduled_run_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


