# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CovalAgentsAPIAgentResourceModelType(str, Enum):
    """
    Agent type returned by the API. Responses can include active types as well as legacy types retained for existing agents. Only values in `SimulatorType` can be supplied when creating or changing an agent type. 
    """

    """
    allowed enum values
    """
    MODEL_TYPE_VOICE = 'MODEL_TYPE_VOICE'
    MODEL_TYPE_OUTBOUND_VOICE = 'MODEL_TYPE_OUTBOUND_VOICE'
    MODEL_TYPE_CHAT = 'MODEL_TYPE_CHAT'
    MODEL_TYPE_CHAT_A2_A = 'MODEL_TYPE_CHAT_A2A'
    MODEL_TYPE_CHAT_WEBSOCKET = 'MODEL_TYPE_CHAT_WEBSOCKET'
    MODEL_TYPE_EMAIL = 'MODEL_TYPE_EMAIL'
    MODEL_TYPE_SMS = 'MODEL_TYPE_SMS'
    MODEL_TYPE_WEBSOCKET = 'MODEL_TYPE_WEBSOCKET'
    MODEL_TYPE_OPENAI_REALTIME = 'MODEL_TYPE_OPENAI_REALTIME'
    MODEL_TYPE_GEMINI_REALTIME = 'MODEL_TYPE_GEMINI_REALTIME'
    MODEL_TYPE_GROK_REALTIME = 'MODEL_TYPE_GROK_REALTIME'
    MODEL_TYPE_DEEPGRAM_REALTIME = 'MODEL_TYPE_DEEPGRAM_REALTIME'
    MODEL_TYPE_TEXT = 'MODEL_TYPE_TEXT'
    MODEL_TYPE_LIVEKIT = 'MODEL_TYPE_LIVEKIT'
    MODEL_TYPE_DAILY = 'MODEL_TYPE_DAILY'
    MODEL_TYPE_NOOP = 'MODEL_TYPE_NOOP'
    MODEL_TYPE_OPENAI_ENDPOINT = 'MODEL_TYPE_OPENAI_ENDPOINT'
    MODEL_TYPE_TRANSCRIPTION = 'MODEL_TYPE_TRANSCRIPTION'
    MODEL_TYPE_TTS = 'MODEL_TYPE_TTS'
    MODEL_TYPE_VOICE_TO_VOICE = 'MODEL_TYPE_VOICE_TO_VOICE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CovalAgentsAPIAgentResourceModelType from a JSON string"""
        return cls(json.loads(json_str))


