# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CovalConversationsAPIConversationStatus(str, Enum):
    """
    Current status of conversation evaluation.  **Lifecycle:** - PENDING: Submitted, awaiting queue - IN_QUEUE: In run-setup-queue, awaiting worker - IN_PROGRESS: Evaluation running - COMPLETED: Successfully completed - FAILED: Encountered error - CANCELLED: User cancelled (via DELETE on PENDING/IN_PROGRESS) - DELETED: Deleted(via DELETE on COMPLETED/FAILED) 
    """

    """
    allowed enum values
    """
    PENDING = 'PENDING'
    IN_QUEUE = 'IN_QUEUE'
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'
    DELETED = 'DELETED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CovalConversationsAPIConversationStatus from a JSON string"""
        return cls(json.loads(json_str))


