# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CovalSlackIntegrationAPISlackStatusResponse(BaseModel):
    """
    Secret-free Slack connection and binding-bootstrap state.
    """ # noqa: E501
    connected: StrictBool = Field(description="Whether a Slack workspace is connected for this organization")
    team_name: Optional[StrictStr] = Field(default=None, description="Connected Slack workspace/team name, or null when not connected")
    enterprise_id: Optional[StrictStr] = Field(default=None, description="Slack Enterprise Grid ID, or null for non-Grid and disconnected states.")
    team_id: Optional[StrictStr] = Field(default=None, description="Slack workspace/team ID when connected.")
    installation_generation: Optional[Annotated[str, Field(min_length=16, strict=True, max_length=128)]] = Field(default=None, description="Opaque backend installation generation used to bind Sofia safely.")
    migration_required: Optional[StrictBool] = Field(default=False, description="Whether an admin must disconnect a legacy physical-store credential before reconnecting.")
    reauthorization_required: Optional[StrictBool] = Field(default=False, description="Whether the routed Slack connection must be reauthorized in place before Sofia can use it.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["connected", "team_name", "enterprise_id", "team_id", "installation_generation", "migration_required", "reauthorization_required"]

    @field_validator('installation_generation')
    def installation_generation_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9_-]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9_-]+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CovalSlackIntegrationAPISlackStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if team_name (nullable) is None
        # and model_fields_set contains the field
        if self.team_name is None and "team_name" in self.model_fields_set:
            _dict['team_name'] = None

        # set to None if enterprise_id (nullable) is None
        # and model_fields_set contains the field
        if self.enterprise_id is None and "enterprise_id" in self.model_fields_set:
            _dict['enterprise_id'] = None

        # set to None if team_id (nullable) is None
        # and model_fields_set contains the field
        if self.team_id is None and "team_id" in self.model_fields_set:
            _dict['team_id'] = None

        # set to None if installation_generation (nullable) is None
        # and model_fields_set contains the field
        if self.installation_generation is None and "installation_generation" in self.model_fields_set:
            _dict['installation_generation'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CovalSlackIntegrationAPISlackStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connected": obj.get("connected"),
            "team_name": obj.get("team_name"),
            "enterprise_id": obj.get("enterprise_id"),
            "team_id": obj.get("team_id"),
            "installation_generation": obj.get("installation_generation"),
            "migration_required": obj.get("migration_required") if obj.get("migration_required") is not None else False,
            "reauthorization_required": obj.get("reauthorization_required") if obj.get("reauthorization_required") is not None else False
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


