# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from coval_sdk.models.coval_monitors_api_monitor_event_outcome import CovalMonitorsAPIMonitorEventOutcome
from coval_sdk.models.coval_monitors_api_monitor_event_resource_condition_results_inner import CovalMonitorsAPIMonitorEventResourceConditionResultsInner
from coval_sdk.models.coval_monitors_api_monitor_event_resource_dispatched_channels_inner import CovalMonitorsAPIMonitorEventResourceDispatchedChannelsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CovalMonitorsAPIMonitorEventResource(BaseModel):
    """
    CovalMonitorsAPIMonitorEventResource
    """ # noqa: E501
    ulid: Annotated[str, Field(strict=True)] = Field(description="Event ULID")
    monitor_ulid: StrictStr = Field(description="Monitor ULID that produced this event")
    run_id: StrictStr = Field(description="Run that triggered evaluation")
    outcome: CovalMonitorsAPIMonitorEventOutcome
    condition_results: Optional[List[CovalMonitorsAPIMonitorEventResourceConditionResultsInner]] = Field(default=None, description="Per-condition evaluation results")
    dispatched_channels: Optional[List[CovalMonitorsAPIMonitorEventResourceDispatchedChannelsInner]] = Field(default=None, description="Per-channel dispatch results")
    message_sent: Optional[StrictStr] = Field(default=None, description="Notification message that was dispatched")
    created_at: datetime = Field(description="Event creation timestamp")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["ulid", "monitor_ulid", "run_id", "outcome", "condition_results", "dispatched_channels", "message_sent", "created_at"]

    @field_validator('ulid')
    def ulid_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9A-Z]{26}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9A-Z]{26}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CovalMonitorsAPIMonitorEventResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in condition_results (list)
        _items = []
        if self.condition_results:
            for _item_condition_results in self.condition_results:
                if _item_condition_results:
                    _items.append(_item_condition_results.to_dict())
            _dict['condition_results'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in dispatched_channels (list)
        _items = []
        if self.dispatched_channels:
            for _item_dispatched_channels in self.dispatched_channels:
                if _item_dispatched_channels:
                    _items.append(_item_dispatched_channels.to_dict())
            _dict['dispatched_channels'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if message_sent (nullable) is None
        # and model_fields_set contains the field
        if self.message_sent is None and "message_sent" in self.model_fields_set:
            _dict['message_sent'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CovalMonitorsAPIMonitorEventResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ulid": obj.get("ulid"),
            "monitor_ulid": obj.get("monitor_ulid"),
            "run_id": obj.get("run_id"),
            "outcome": obj.get("outcome"),
            "condition_results": [CovalMonitorsAPIMonitorEventResourceConditionResultsInner.from_dict(_item) for _item in obj["condition_results"]] if obj.get("condition_results") is not None else None,
            "dispatched_channels": [CovalMonitorsAPIMonitorEventResourceDispatchedChannelsInner.from_dict(_item) for _item in obj["dispatched_channels"]] if obj.get("dispatched_channels") is not None else None,
            "message_sent": obj.get("message_sent"),
            "created_at": obj.get("created_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


