# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from coval_sdk.models.coval_templates_api_simulation_type import CovalTemplatesAPISimulationType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CovalTemplatesAPITemplateResource(BaseModel):
    """
    Template configuration resource for reusable simulation setups.  Templates define complete simulation configurations including agent references, customer prompts, metrics, personas, and execution parameters. 
    """ # noqa: E501
    id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Template resource ID")
    name: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Resource name (templates/{id})")
    template_name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=200)]] = Field(default=None, description="Human-readable template name")
    description: Optional[Annotated[str, Field(strict=True, max_length=1000)]] = Field(default=None, description="Template description")
    simulation_type: Optional[CovalTemplatesAPISimulationType] = None
    simulation_metadata: Optional[Dict[str, Any]] = Field(default=None, description="Simulation-specific configuration (JSONB)")
    simulated_user_prompt: Optional[StrictStr] = Field(default=None, description="Instructions for the simulated customer behavior")
    agent_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Associated agent ID")
    enabled_metrics: Optional[List[StrictStr]] = Field(default=None, description="List of metric IDs to evaluate")
    persona_ids: Optional[List[StrictStr]] = Field(default=None, description="List of persona IDs for customer simulation")
    test_set_id: Optional[StrictStr] = Field(default=None, description="Associated test set ID")
    iteration_count: Optional[Annotated[int, Field(le=10000, strict=True, ge=1)]] = Field(default=1, description="Number of simulation iterations to run")
    concurrency: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=1, description="Number of parallel simulations to run")
    sub_sample_size: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Maximum number of test cases to sample from test set")
    test_case_params_by_iteration: Optional[List[Dict[str, Any]]] = Field(default=None, description="Per-iteration parameter overrides (JSONB array)")
    create_time: Optional[datetime] = Field(default=None, description="Creation timestamp (ISO 8601)")
    update_time: Optional[datetime] = Field(default=None, description="Last update timestamp (ISO 8601)")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "name", "template_name", "description", "simulation_type", "simulation_metadata", "simulated_user_prompt", "agent_id", "enabled_metrics", "persona_ids", "test_set_id", "iteration_count", "concurrency", "sub_sample_size", "test_case_params_by_iteration", "create_time", "update_time"]

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9]{22}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9]{22}$/")
        return value

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^templates\/[A-Za-z0-9]{22}$", value):
            raise ValueError(r"must validate the regular expression /^templates\/[A-Za-z0-9]{22}$/")
        return value

    @field_validator('agent_id')
    def agent_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9]{22}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9]{22}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CovalTemplatesAPITemplateResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if simulated_user_prompt (nullable) is None
        # and model_fields_set contains the field
        if self.simulated_user_prompt is None and "simulated_user_prompt" in self.model_fields_set:
            _dict['simulated_user_prompt'] = None

        # set to None if persona_ids (nullable) is None
        # and model_fields_set contains the field
        if self.persona_ids is None and "persona_ids" in self.model_fields_set:
            _dict['persona_ids'] = None

        # set to None if test_set_id (nullable) is None
        # and model_fields_set contains the field
        if self.test_set_id is None and "test_set_id" in self.model_fields_set:
            _dict['test_set_id'] = None

        # set to None if sub_sample_size (nullable) is None
        # and model_fields_set contains the field
        if self.sub_sample_size is None and "sub_sample_size" in self.model_fields_set:
            _dict['sub_sample_size'] = None

        # set to None if update_time (nullable) is None
        # and model_fields_set contains the field
        if self.update_time is None and "update_time" in self.model_fields_set:
            _dict['update_time'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CovalTemplatesAPITemplateResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "template_name": obj.get("template_name"),
            "description": obj.get("description"),
            "simulation_type": obj.get("simulation_type"),
            "simulation_metadata": obj.get("simulation_metadata"),
            "simulated_user_prompt": obj.get("simulated_user_prompt"),
            "agent_id": obj.get("agent_id"),
            "enabled_metrics": obj.get("enabled_metrics"),
            "persona_ids": obj.get("persona_ids"),
            "test_set_id": obj.get("test_set_id"),
            "iteration_count": obj.get("iteration_count") if obj.get("iteration_count") is not None else 1,
            "concurrency": obj.get("concurrency") if obj.get("concurrency") is not None else 1,
            "sub_sample_size": obj.get("sub_sample_size"),
            "test_case_params_by_iteration": obj.get("test_case_params_by_iteration"),
            "create_time": obj.get("create_time"),
            "update_time": obj.get("update_time")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


