# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from coval_sdk.models.coval_reviews_api_annotation_priority import CovalReviewsAPIAnnotationPriority
from coval_sdk.models.coval_reviews_api_annotation_status import CovalReviewsAPIAnnotationStatus
from coval_sdk.models.coval_reviews_api_completion_status import CovalReviewsAPICompletionStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CovalReviewsAPIReviewAnnotationResource(BaseModel):
    """
    A single review annotation resource.
    """ # noqa: E501
    name: StrictStr = Field(description="Resource name: review-annotations/{id}")
    id: StrictStr = Field(description="Unique annotation ID")
    simulation_output_id: StrictStr = Field(description="Linked simulation output ID")
    metric_id: StrictStr = Field(description="Linked metric ID")
    assignee: StrictStr = Field(description="Email of the assigned reviewer")
    ground_truth_float_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Reviewer-provided ground truth numeric value")
    ground_truth_string_value: Optional[StrictStr] = Field(default=None, description="Reviewer-provided ground truth string value")
    ground_truth_subvalues_by_timestamp: Optional[List[Dict[str, Any]]] = Field(default=None, description="Reviewer-provided ground truth subvalues keyed by timestamp")
    reviewer_notes: Optional[StrictStr] = Field(default=None, description="Free-text reviewer notes")
    status: CovalReviewsAPIAnnotationStatus
    completion_status: CovalReviewsAPICompletionStatus
    priority: CovalReviewsAPIAnnotationPriority
    create_time: datetime = Field(description="Creation timestamp (ISO 8601)")
    update_time: datetime = Field(description="Last update timestamp (ISO 8601)")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "id", "simulation_output_id", "metric_id", "assignee", "ground_truth_float_value", "ground_truth_string_value", "ground_truth_subvalues_by_timestamp", "reviewer_notes", "status", "completion_status", "priority", "create_time", "update_time"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CovalReviewsAPIReviewAnnotationResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if ground_truth_float_value (nullable) is None
        # and model_fields_set contains the field
        if self.ground_truth_float_value is None and "ground_truth_float_value" in self.model_fields_set:
            _dict['ground_truth_float_value'] = None

        # set to None if ground_truth_string_value (nullable) is None
        # and model_fields_set contains the field
        if self.ground_truth_string_value is None and "ground_truth_string_value" in self.model_fields_set:
            _dict['ground_truth_string_value'] = None

        # set to None if ground_truth_subvalues_by_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.ground_truth_subvalues_by_timestamp is None and "ground_truth_subvalues_by_timestamp" in self.model_fields_set:
            _dict['ground_truth_subvalues_by_timestamp'] = None

        # set to None if reviewer_notes (nullable) is None
        # and model_fields_set contains the field
        if self.reviewer_notes is None and "reviewer_notes" in self.model_fields_set:
            _dict['reviewer_notes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CovalReviewsAPIReviewAnnotationResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "id": obj.get("id"),
            "simulation_output_id": obj.get("simulation_output_id"),
            "metric_id": obj.get("metric_id"),
            "assignee": obj.get("assignee"),
            "ground_truth_float_value": obj.get("ground_truth_float_value"),
            "ground_truth_string_value": obj.get("ground_truth_string_value"),
            "ground_truth_subvalues_by_timestamp": obj.get("ground_truth_subvalues_by_timestamp"),
            "reviewer_notes": obj.get("reviewer_notes"),
            "status": obj.get("status"),
            "completion_status": obj.get("completion_status"),
            "priority": obj.get("priority") if obj.get("priority") is not None else CovalReviewsAPIAnnotationPriority.PRIORITY_STANDARD,
            "create_time": obj.get("create_time"),
            "update_time": obj.get("update_time")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


