# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CovalMetricsAPIAgentJudgeRuntimeTool(str, Enum):
    """
    Evidence tool that may appear in persisted Agent Judge metric metadata.
    """

    """
    allowed enum values
    """
    GET_TRANSCRIPT = 'get_transcript'
    SEARCH_TRANSCRIPT = 'search_transcript'
    SEARCH_TRANSCRIPT_REGEX = 'search_transcript_regex'
    GET_TRACE_SPANS = 'get_trace_spans'
    QUERY_SIMULATION_FRAMES = 'query_simulation_frames'
    GET_RUN_CONTEXT = 'get_run_context'
    QUERY_JEV = 'query_jev'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CovalMetricsAPIAgentJudgeRuntimeTool from a JSON string"""
        return cls(json.loads(json_str))


