# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from coval_sdk.models.coval_reviews_api_review_annotation_resource import CovalReviewsAPIReviewAnnotationResource
from coval_sdk.models.coval_reviews_api_review_metric_output_for_annotation_resource import CovalReviewsAPIReviewMetricOutputForAnnotationResource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CovalReviewsAPIGetAnnotationsWithMetricOutputsResponse(BaseModel):
    """
    CovalReviewsAPIGetAnnotationsWithMetricOutputsResponse
    """ # noqa: E501
    annotations: Dict[str, List[CovalReviewsAPIReviewAnnotationResource]] = Field(description="Annotations keyed by metric ID.")
    metric_outputs: Dict[str, Dict[str, CovalReviewsAPIReviewMetricOutputForAnnotationResource]] = Field(description="Latest pipeline metric output keyed by metric ID then simulation output ID.")
    audio_lengths_by_simulation_output_id: Dict[str, Optional[Union[StrictFloat, StrictInt]]]
    next_page_token: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["annotations", "metric_outputs", "audio_lengths_by_simulation_output_id", "next_page_token"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CovalReviewsAPIGetAnnotationsWithMetricOutputsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in annotations (dict of array)
        _field_dict_of_array = {}
        if self.annotations:
            for _key_annotations in self.annotations:
                if self.annotations[_key_annotations] is not None:
                    _field_dict_of_array[_key_annotations] = [
                        _item.to_dict() for _item in self.annotations[_key_annotations]
                    ]
            _dict['annotations'] = _field_dict_of_array
        # override the default output from pydantic by calling `to_dict()` of each value in metric_outputs (dict of dict)
        _field_dict_of_dict = {}
        if self.metric_outputs:
            for _key_metric_outputs, _value_metric_outputs in self.metric_outputs.items():
                if _value_metric_outputs is not None:
                    _field_dict_of_dict[_key_metric_outputs] = {
                        _key: _value.to_dict() for _key, _value in _value_metric_outputs.items()
                    }
            _dict['metric_outputs'] = _field_dict_of_dict
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if next_page_token (nullable) is None
        # and model_fields_set contains the field
        if self.next_page_token is None and "next_page_token" in self.model_fields_set:
            _dict['next_page_token'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CovalReviewsAPIGetAnnotationsWithMetricOutputsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "annotations": {
                _k: [CovalReviewsAPIReviewAnnotationResource.from_dict(_item) for _item in _v] if _v is not None else None
                for _k, _v in obj["annotations"].items()
            }
            if obj.get("annotations") is not None
            else None,
            "metric_outputs": dict(
                (_k, dict(
                    (_ik, CovalReviewsAPIReviewMetricOutputForAnnotationResource.from_dict(_iv))
                        for _ik, _iv in _v.items()
                    )
                    if _v is not None
                    else None
                )
                for _k, _v in obj["metric_outputs"].items()
            )
            if obj.get("metric_outputs") is not None
            else None,
            "audio_lengths_by_simulation_output_id": obj.get("audio_lengths_by_simulation_output_id"),
            "next_page_token": obj.get("next_page_token")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


