# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CovalReportsAPIReportPermission(str, Enum):
    """
    PUBLIC creates a login-free shareable report; PRIVATE keeps it organization-only.
    """

    """
    allowed enum values
    """
    PUBLIC = 'PUBLIC'
    PRIVATE = 'PRIVATE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CovalReportsAPIReportPermission from a JSON string"""
        return cls(json.loads(json_str))


