# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from coval_sdk.models.coval_runs_api_launch_metadata import CovalRunsAPILaunchMetadata
from coval_sdk.models.coval_runs_api_launch_options import CovalRunsAPILaunchOptions
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CovalRunsAPILaunchRunRequest(BaseModel):
    """
    CovalRunsAPILaunchRunRequest
    """ # noqa: E501
    agent_id: Annotated[str, Field(min_length=22, strict=True, max_length=22)] = Field(description="The agent to test. Must be owned by the authenticated organization.")
    persona_id: Annotated[str, Field(min_length=22, strict=True, max_length=22)] = Field(description="The simulated persona to use for testing.")
    test_set_id: Annotated[str, Field(min_length=8, strict=True, max_length=8)] = Field(description="The test set containing test cases to run.")
    metric_ids: Optional[List[Annotated[str, Field(min_length=22, strict=True, max_length=22)]]] = Field(default=None, description="Optional list of metric IDs to evaluate. If not provided, uses agent's default metrics.")
    mutation_id: Optional[Annotated[str, Field(min_length=26, strict=True, max_length=26)]] = Field(default=None, description="Single mutation ID to run in addition to the base agent. Mutually exclusive with `mutation_ids`. The base agent always runs. ")
    mutation_ids: Optional[Annotated[List[Annotated[str, Field(min_length=26, strict=True, max_length=26)]], Field(max_length=100)]] = Field(default=None, description="List of mutation IDs to run in addition to the base agent. Mutually exclusive with `mutation_id`. Max 100 mutations. The base agent always runs alongside all mutations.  **Total simulations** = test_cases × iterations × (1 + len(mutation_ids)) ")
    persona_metrics: Optional[List[StrictStr]] = Field(default=None, description="List of metric names that should evaluate the persona instead of the agent. Each entry should be the base metric name (e.g., 'latency', not 'persona:latency'). ")
    options: Optional[CovalRunsAPILaunchOptions] = None
    metadata: Optional[CovalRunsAPILaunchMetadata] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["agent_id", "persona_id", "test_set_id", "metric_ids", "mutation_id", "mutation_ids", "persona_metrics", "options", "metadata"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CovalRunsAPILaunchRunRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of options
        if self.options:
            _dict['options'] = self.options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if mutation_id (nullable) is None
        # and model_fields_set contains the field
        if self.mutation_id is None and "mutation_id" in self.model_fields_set:
            _dict['mutation_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CovalRunsAPILaunchRunRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_id": obj.get("agent_id"),
            "persona_id": obj.get("persona_id"),
            "test_set_id": obj.get("test_set_id"),
            "metric_ids": obj.get("metric_ids"),
            "mutation_id": obj.get("mutation_id"),
            "mutation_ids": obj.get("mutation_ids"),
            "persona_metrics": obj.get("persona_metrics"),
            "options": CovalRunsAPILaunchOptions.from_dict(obj["options"]) if obj.get("options") is not None else None,
            "metadata": CovalRunsAPILaunchMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


