# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from coval_sdk.deserialization import deserialize_model_list
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from coval_sdk.models.test_sets_api_test_set_resource import TestSetsAPITestSetResource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListTestSets200Response(BaseModel):
    """
    ListTestSets200Response
    """ # noqa: E501
    test_sets: Optional[List[TestSetsAPITestSetResource]] = None
    next_page_token: Optional[StrictStr] = Field(default=None, description="Token for retrieving the next page (empty if last page)")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["test_sets", "next_page_token"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListTestSets200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in test_sets (list)
        _items = []
        if self.test_sets:
            for _item_test_sets in self.test_sets:
                if _item_test_sets:
                    _items.append(_item_test_sets.to_dict())
            _dict['test_sets'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListTestSets200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "test_sets": deserialize_model_list(obj["test_sets"], TestSetsAPITestSetResource, response_model="ListTestSets200Response", field="test_sets") if obj.get("test_sets") is not None else None,
            "next_page_token": obj.get("next_page_token")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


