# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from coval_sdk.models.test_sets_api_test_set_record_resource_expected_output import TestSetsAPITestSetRecordResourceExpectedOutput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TestSetsAPITestSetRecordResource(BaseModel):
    """
    TestSetsAPITestSetRecordResource
    """ # noqa: E501
    id: StrictStr
    input: StrictStr = Field(description="Test case input string.")
    input_type: Optional[StrictStr] = None
    expected_behaviors: Optional[List[StrictStr]] = None
    expected_output: Optional[TestSetsAPITestSetRecordResourceExpectedOutput] = None
    description: Optional[StrictStr] = None
    user_notes: Optional[StrictStr] = None
    create_time: Optional[datetime] = None
    update_time: Optional[datetime] = None
    test_set_id: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "input", "input_type", "expected_behaviors", "expected_output", "description", "user_notes", "create_time", "update_time", "test_set_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestSetsAPITestSetRecordResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of expected_output
        if self.expected_output:
            _dict['expected_output'] = self.expected_output.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if input_type (nullable) is None
        # and model_fields_set contains the field
        if self.input_type is None and "input_type" in self.model_fields_set:
            _dict['input_type'] = None

        # set to None if expected_output (nullable) is None
        # and model_fields_set contains the field
        if self.expected_output is None and "expected_output" in self.model_fields_set:
            _dict['expected_output'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if user_notes (nullable) is None
        # and model_fields_set contains the field
        if self.user_notes is None and "user_notes" in self.model_fields_set:
            _dict['user_notes'] = None

        # set to None if create_time (nullable) is None
        # and model_fields_set contains the field
        if self.create_time is None and "create_time" in self.model_fields_set:
            _dict['create_time'] = None

        # set to None if update_time (nullable) is None
        # and model_fields_set contains the field
        if self.update_time is None and "update_time" in self.model_fields_set:
            _dict['update_time'] = None

        # set to None if test_set_id (nullable) is None
        # and model_fields_set contains the field
        if self.test_set_id is None and "test_set_id" in self.model_fields_set:
            _dict['test_set_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestSetsAPITestSetRecordResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "input": obj.get("input"),
            "input_type": obj.get("input_type"),
            "expected_behaviors": obj.get("expected_behaviors"),
            "expected_output": TestSetsAPITestSetRecordResourceExpectedOutput.from_dict(obj["expected_output"]) if obj.get("expected_output") is not None else None,
            "description": obj.get("description"),
            "user_notes": obj.get("user_notes"),
            "create_time": obj.get("create_time"),
            "update_time": obj.get("update_time"),
            "test_set_id": obj.get("test_set_id")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


