# coding: utf-8

"""
    Coval Agents API

     Manage configurations for simulations and evaluations. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@coval.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from coval_sdk.models.non_script_test_case import NonSCRIPTTestCase
from coval_sdk.models.script_test_case_with_legacy_nested_turns import SCRIPTTestCaseWithLegacyNestedTurns
from coval_sdk.models.script_test_case_with_top_level_turns import SCRIPTTestCaseWithTopLevelTurns
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

TESTCASESAPICREATETESTCASEREQUEST_ANY_OF_SCHEMAS = ["NonSCRIPTTestCase", "SCRIPTTestCaseWithLegacyNestedTurns", "SCRIPTTestCaseWithTopLevelTurns"]

class TestCasesAPICreateTestCaseRequest(BaseModel):
    """
    Request body for creating a test case
    """

    # data type: NonSCRIPTTestCase
    anyof_schema_1_validator: Optional[NonSCRIPTTestCase] = None
    # data type: SCRIPTTestCaseWithTopLevelTurns
    anyof_schema_2_validator: Optional[SCRIPTTestCaseWithTopLevelTurns] = None
    # data type: SCRIPTTestCaseWithLegacyNestedTurns
    anyof_schema_3_validator: Optional[SCRIPTTestCaseWithLegacyNestedTurns] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[NonSCRIPTTestCase, SCRIPTTestCaseWithLegacyNestedTurns, SCRIPTTestCaseWithTopLevelTurns]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "NonSCRIPTTestCase", "SCRIPTTestCaseWithLegacyNestedTurns", "SCRIPTTestCaseWithTopLevelTurns" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = TestCasesAPICreateTestCaseRequest.model_construct()
        error_messages = []
        # validate data type: NonSCRIPTTestCase
        if not isinstance(v, NonSCRIPTTestCase):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NonSCRIPTTestCase`")
        else:
            return v

        # validate data type: SCRIPTTestCaseWithTopLevelTurns
        if not isinstance(v, SCRIPTTestCaseWithTopLevelTurns):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SCRIPTTestCaseWithTopLevelTurns`")
        else:
            return v

        # validate data type: SCRIPTTestCaseWithLegacyNestedTurns
        if not isinstance(v, SCRIPTTestCaseWithLegacyNestedTurns):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SCRIPTTestCaseWithLegacyNestedTurns`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in TestCasesAPICreateTestCaseRequest with anyOf schemas: NonSCRIPTTestCase, SCRIPTTestCaseWithLegacyNestedTurns, SCRIPTTestCaseWithTopLevelTurns. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[NonSCRIPTTestCase] = None
        try:
            instance.actual_instance = NonSCRIPTTestCase.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[SCRIPTTestCaseWithTopLevelTurns] = None
        try:
            instance.actual_instance = SCRIPTTestCaseWithTopLevelTurns.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[SCRIPTTestCaseWithLegacyNestedTurns] = None
        try:
            instance.actual_instance = SCRIPTTestCaseWithLegacyNestedTurns.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into TestCasesAPICreateTestCaseRequest with anyOf schemas: NonSCRIPTTestCase, SCRIPTTestCaseWithLegacyNestedTurns, SCRIPTTestCaseWithTopLevelTurns. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], NonSCRIPTTestCase, SCRIPTTestCaseWithLegacyNestedTurns, SCRIPTTestCaseWithTopLevelTurns]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


